version: '2'

services:
  loqusdbapi:
    build: .
    platform: linux/amd64 # forces x86_64, avoids cyvcf2 ARM issues
    ports:
      - 9000:8000
    links:
      - mongo:mongo
    environment:
      URI: mongodb://mongo:27017/loqusdb
      MODULE_NAME: "loqusdbapi.main"

  mongo:
    image: mongo:7

  restore:
    image: mongo:7
    volumes:
      - ./dump:/var/dump
    links:
      - mongo:mongo
    command: mongorestore --host mongo:27017 -d loqusdb /var/dump/
