name: Push loqusdbapi mage to Docker Hub

on:
  pull_request:
    types: [ closed ]

jobs:
  docker-image-CI:
    # Push to Docker Hub only if PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
     - name: Check out git repository
       uses: actions/checkout@v2

     - name: Build and publish to Docker Hub
       uses: elgohr/Publish-Docker-Github-Action@master
       with:
         name: clinicalgenomics/loqusdbapi
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         tags: "latest"
